[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    symlink://../..

[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
