[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    symlink://../..
    arduino-libraries/Ethernet
lib_ldf_mode = deep+
build_flags =
    -DNTP_UDP_IMPLEMENTATION=\"EthernetUdp.h\"
    -DNTP_UDP_CLASS=EthernetUDP
    -DNTP_DEBUG
    ; Expose the Arduino Ethernet headers to the NTPClient library compile unit,
    ; which is built without dependencies and otherwise cannot see EthernetUdp.h.
    -I.pio/libdeps/esp32dev/Ethernet/src

[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
